### ISSUE TITLE
iTunes will complain about missing entitlements when using SOXAppDelegate because didRegisterForRemoteNotificationsWithDeviceToken: is implemented

### ISSUE THREAD

**Issue by hokster7** [floriankrueger/SOXAppDelegate#3]
I got this rather nice automated e-mail after integrating SOXAppDelegate.

```
Dear developer,

We have discovered one or more issues with your recent delivery for "Loaf". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team
```

This should definitely be documented in the README.

**Comment by floriankrueger** [comment]
Hi fatuhoku, I just pushed a new release (1.1.1) to trunk. can you please verify that this solution is working for you?

**Comment by hokster7** [comment]
Hi @floriankrueger,

Unfortunately the fix has not worked. We still get the e-mails from iTunes Connect. I just upgraded to 1.1.1 without touching a thing (didn't set any of the preprocessor flags) so I'm not sure what happened here.

**Comment by hokster7** [comment]
@floriankrueger it's probably because your fix only disables one of **three** methods to do with remote notifications. i.e. the following also need to be disabled:

```
-application:didRegisterForRemoteNotificationsWithDeviceToken:
-application:didFailToRegisterForRemoteNotificationsWithError:
```
